version: '2'
services:
  db:
    image: keinos/sqlite3:3.42.0
    stdin_open: true
    tty: true
    volumes:
      - ./db/:/root/db/  
  app:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ".:/niki"
    ports: 
      - "3001:3000" #host_port:guest_port
    depends_on:
      - db
    links:
      - db
  