default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: askani
  password: admin123

development:
  <<: *default
  database: credittracker

test:
  <<: *default
  database: credittrackertest

production:
  <<: *default
  database: credittracker
  username: askani
  password: admin123
