# .github/workflows/rails_heroku_deploy.yml

name: CI/CD Pipeline

on:
  push:
    branches:
      - iteration-2-dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # - name: Checkout Code
    #   uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.2 # Set to your Ruby version
    - name: Check GitHub Workspace
      run: echo ${{ github.workspace }}

    - name: Install Bundler
      run: |
         cd ${{ github.workspace }}
         gem install bundler
      working-directory: ${{ github.workspace }}
     

    - name: Install Dependencies
      run: |
         cd ${{ github.workspace }}
         bundle install
      working-directory: ${{ github.workspace }}

    - name: Database Setup
      run: | 
         cd ${{ github.workspace }}
         bundle exec rails db:create db:migrate
      working-directory: ${{ github.workspace }}

    - name: Run Tests
      run:  cd ${{ github.workspace }}
         bundle exec rspec
      working-directory: ${{ github.workspace }}
      

    - name: Deploy to Heroku
      run: |
        git remote add heroku https://git.heroku.com/csce606-niki.git
        git push heroku main
