name: CI/CD Pipeline

on:
  push:
    branches:
      - ci/cd

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.2 # Set to your Ruby version

    - name: Install Bundler
      run: gem install bundler

    - name: Install dependencies
      run: bundle install

    # - name: Run tests
    #   run: bundle exec rake test

    - name: Deploy to Heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        heroku git:remote -a csce606-niki
        git push heroku main
    - name: Create and Migrate Database
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        heroku run rails db:create --app csce606-niki
        heroku run rails db:migrate --app csce606-niki
