# .github/workflows/rails_heroku_deploy.yml

name: CI/CD Pipeline

on:
  push:
    branches:
      - iteration-2-dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.2 # Set to your Ruby version

    - name: Install Bundler
      run: gem install bundler

    - name: Install Dependencies
      run: bundle install
      
    - name: Install Heroku CLI
      uses: heroku/heroku@v5

    - name: Login to Heroku
      run: |
        echo $HEROKU_API_KEY | heroku login --interactive
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}  # Set your Heroku API key as a GitHub secret

    - name: Access Heroku Database
      run: |
        DATABASE_URL=$(heroku config:get DATABASE_URL -a your-heroku-app-name)  # Replace 'your-heroku-app-name' with your app name
        echo "Database URL: $DATABASE_URL"
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

    - name: Run Database Migrations
      run: |
        # You can use the DATABASE_URL environment variable to run database migrations
        bundle exec rails db:migrate
      env:
        DATABASE_URL: $DATABASE_URL

    - name: Database Setup
      run: heroku run rake db:create db:migrate

    - name: Run Tests
      run: bundle exec rspec

    - name: Deploy to Heroku
      run: |
        git remote add heroku https://git.heroku.com/csce606-niki.git
        git push heroku main
